#!/bin/bash
#$ -S /bin/bash
#$ -cwd

HOME=/home/research/tanglab-runner/
TASK_QUEUE='http://www.microbesflux.org/flux/task/mark/?tid='
TASK_FOLDER=task_queue/
TASK_STATUS_START='&status=PLOT_START'
TASK_STATUS_END='&status=PLOT_END'
TASK_STATUS_FAIL='&status=PLOT_FAIL'
FILE=${HOME}${TASK_FOLDER}${UUID}

export PATH=${HOME}bin:/cluster/cloud/bin:$PATH

echo "Going to mark current task "
wget --spider ${TASK_QUEUE}${TID}${TASK_STATUS_START}

echo "Going to call python to plot the current adjlist. Job name is ${UUID}"
if [ -e ${FILE}.adjlist ]
then echo "Found the adjlist file generated by MF, sending to python"
${HOME}/bin/python ${HOME}/script/plot.py ${FILE}.adjlist
fi
if [ -e ${FILE}.adjlist_plot.svg ]
then echo "SVG generated."
 cat ${FILE}.adjlist_plot.svg | sed "s/stroke-width: 1.000000/stroke-width: 0.100000/g"  > ${FILE}.svg
 rm ${FILE}.adjlist_plot.svg
 wget --spider ${TASK_QUEUE}${TID}${TASK_STATUS_END}
else
 wget --spider ${TASK_QUEUE}${TID}${TASK_STATUS_FAIL}
fi
